<?php

/**
 * @file
 * Static Deploy module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\static_build\Plugin\StaticBuilderPluginInterface;

/**
 * Implements hook_help().
 */
function static_deploy_help($route_name, RouteMatchInterface $route_match): string {
  if ($route_name === 'help.page.static_deploy') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('Base module that enables the deployment of sites built by Static Build to different CDN/hosting services.') . '</p>';
    $output .= '<h3>' . t('Uses') . '</h3>';
    $output .= '<dl>';
    $output .= '<dt>' . t('Base module for deploying your static site') . '</dt>';
    $output .= '<dd>' . t('This module serves as an orchestrator for the process of deploying a site, and should be complemented with a compatible "static deployer" module.') . '</dd>';
    $output .= '</dl>';
    return $output;
  }
  return '';
}

/**
 * Implements hook_toolbar().
 *
 * Displays a progress bar in the toolbar to view the progress of a deploy.
 *
 * Visible in:
 *  - administration pages.
 *
 * Not visible in:
 *  - system.batch_page.html route.
 *  - static_suite.admin_reports route.
 *  - when the user does not have permissions.
 */
function static_deploy_toolbar(): array {
  $emptyItem = [
    '#weight' => 9999,
    '#type' => 'toolbar_item',
    '#cache' => ['max-age' => 0],
    'tab' => [
      '#type' => 'inline_template',
      '#template' => '',
    ],
  ];

  if (!static_suite_is_progress_bar_in_toolbar_allowed('view reports of deploys on toolbar')) {
    return $emptyItem;
  }

  $runMode = StaticBuilderPluginInterface::RUN_MODE_LIVE;

  /** @var \Drupal\static_build\Plugin\StaticBuilderPluginManagerInterface $staticBuilderPluginManager */
  $staticBuilderPluginManager = Drupal::service('plugin.manager.static_builder');
  /** @var \Drupal\static_deploy\Plugin\StaticDeployerPluginManagerInterface $staticDeployerPluginManager */
  $staticDeployerPluginManager = Drupal::service('plugin.manager.static_deployer');
  /** @var \Drupal\Core\Session\AccountProxyInterface $currentUser */
  $currentUser = Drupal::service('current_user');

  $localBuilderDefinitions = $staticBuilderPluginManager->getLocalDefinitions();
  $deployerDefinitions = $staticDeployerPluginManager->getDefinitions();

  /** @var \Drupal\Core\Config\ConfigFactoryInterface $configFactory */
  $configFactory = \Drupal::service('config.factory');
  $config = $configFactory->get('static_deploy.settings');
  $toolbarEnabled = $config->get('toolbar');

  if ($toolbarEnabled && is_array($localBuilderDefinitions) && is_array($deployerDefinitions) &&
    count($localBuilderDefinitions) > 0 && count($deployerDefinitions) > 0) {
    $enabledDeployerIds = $config->get('deployers');
    foreach ($localBuilderDefinitions as $builderDefinition) {
      foreach ($deployerDefinitions as $deployerDefinition) {
        // Filter out non-enabled deployers.
        if (in_array($deployerDefinition['id'], $enabledDeployerIds, TRUE)) {
          $batchUri = Url::fromRoute('static_deploy.release_list.running_data.batch', [
            'deployerId' => $deployerDefinition['id'],
            'builderId' => $builderDefinition['id'],
            'destination' => '_none',
          ])->toString();

          $title = $builderDefinition['label'] . ' - ' . $deployerDefinition['label'] . ' - ' . $runMode;
          if ($currentUser->hasPermission('access site reports')) {
            $title = [
              '#type' => 'link',
              '#url' => Url::fromRoute('static_deployer_' . $deployerDefinition['id'] . '.release_list.live', [
                'builderId' => $builderDefinition['id'],
              ]),
              '#title' => $builderDefinition['label'] . ' - ' . $deployerDefinition['label'] . ' - ' . $runMode,
              '#attributes' => [
                'target' => '_blank',
                'title' => t('View build list'),
              ],
              '#cache' => ['max-age' => 0],
            ];
          }

          $items['static-deploy-task-' . $builderDefinition['id'] . '-' . $runMode . '-' . $deployerDefinition['id']] = [
            '#weight' => 9999,
            '#type' => 'toolbar_item',
            '#cache' => ['max-age' => 0],
            'tab' => [
              '#type' => 'inline_template',
              '#attached' => [
                'library' => ['static_suite/toolbar-progress-bar'],
              ],
              static_suite_progress_bar_theme($batchUri, $title),
            ],
          ];
        }
      }
    }

    return $items ?? $emptyItem;
  }

  return $emptyItem;
}