name: Config Suite
type: module
description: Config Suite is a set of improvements to the configuration management sto make it easier to work with.
core_version_requirement: ^9
package: Custom
configure: config_suite.config_suite_form

# Information added by Drupal.org packaging script on 2022-06-23
version: '2.0.3'
project: 'config_suite'
datestamp: 1655944668
