<?php

/**
 * @file
 * Static Export GraphQL Data Resolver module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function static_export_data_resolver_graphql_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.static_export_data_resolver_graphql':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t(
          'Provides a GraphQL data resolver for Static Export module, part of the <a href=":static-suite-url">Static Suite</a> module. This module is one of the multiple data resolvers available for Static Export.',
          [':static-suite-url' => 'https://www.drupal.org/project/static_suite']
        ) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Exporting data from a GraphQL endpoint') . '</dt>';
      $output .= '<dd>' . t('Static Export export your entities to plain files. Data for those entities can be gathered from different sources, like JSON:API or GraphQL. This module obtains data from a GraphQL endpoint, executing a query defined per each entity type and bundle.') . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_requirements().
 *
 * Do not know why, but moving this function to
 * static_export_data_resolver_graphql.install makes Drupal not discovering and
 * not executing it.
 */
function static_export_data_resolver_graphql_requirements($phase): array {
  $requirements = [];

  if ($phase === 'runtime') {
    $outputFormatterDefinitions = Drupal::service('plugin.manager.static_output_formatter')
      ->getDefinitions();
    if (count($outputFormatterDefinitions) === 0) {
      $requirements['static_export_data_resolver_graphql_missing_output_formatter'] = [
        'title' => t('Static Export - Data Resolver - GraphQL'),
        'severity' => REQUIREMENT_ERROR,
        'value' => t('Missing output formatter'),
        'description' => t('No output formatter available, please install one of the default output formatters provided by Static Suite (static_export_output_formatter_json -recommended-, static_export_output_formatter_xml and static_export_output_formatter_yaml) or create your own one.'),
      ];
    }
  }

  return $requirements;
}

