<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function static_preview_gatsby_instant_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.static_preview_gatsby_instant_help':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module enables an instant preview system for sites built by "Static Builder - Gatsby" module, which is a plugin for Static Build module. It is "instant" because there is no need to run a build to visualize changes.') . '</p>';
      return $output;
  }
}


/**
 * Implements hook_form_alter().
 * function static_preview_gatsby_instant_form_alter(&$form, FormStateInterface
 * $form_state, $form_id) {
 * $exportableEntitiesThatAreStatifiedPages =
 * \Drupal::service('static_export.exportable_entity_manager')->getExportableEntitiesThatAreStatifiedPages();
 * $validFormIds = [];
 * foreach ($exportableEntitiesThatAreStatifiedPages as $exportableEntity) {
 * $validFormIds[] = $exportableEntity->getEntityTypeIdString() . "_" .
 * $exportableEntity->getBundle() . "_form";
 * $validFormIds[] = $exportableEntity->getEntityTypeIdString() . "_" .
 * $exportableEntity->getBundle() . "_edit_form";
 * }
 * if (in_array($form_id, $validFormIds, TRUE)) {
 * // Use a fixed value for target, so preview  opens always in the same tab.
 * $form['actions']['preview']['#attributes']['onclick'] =
 * 'this.form.target="preview";return true;';
 * }
 * }
 */
