# Schema for the configuration files of the static_export_exporter_redirect module.
static_export_exporter_redirect.settings:
  type: config_object
  label: 'Static Export redirect exporter settings'
  mapping:
    format:
      type: string
      label: 'Export format for redirects'
    csv:
      type: mapping
      label: 'CSV configuration'
      mapping:
        pattern:
          type: string
          label: 'Line pattern for the CSV format'
