static_export_output_formatter_json.settings:
  type: config_object
  label: 'Settings for JSON output formatter'
  mapping:
    pretty_print:
      type: boolean
      label: 'Pretty-print JSON data'
