name: Config Export Ignore
type: module
description: Allows to ignore configurations while exporting via config split
core: 8.x
package: Config
core_version_requirement: ^8 || ^9
dependencies:
  - config_split:config_split

# Information added by Drupal.org packaging script on 2020-09-22
version: '8.x-1.1'
project: 'config_export_ignore'
datestamp: 1600790197
