<?php

/**
 * @file
 * Module implementation file.
 */

use Drupal\Core\Routing\RouteObjectInterface;

/**
 * Implements hook_file_url_alter().
 */
function cl_server_file_url_alter(&$uri) {
  $request = \Drupal::request();
  $route_name = $request->attributes->get(RouteObjectInterface::ROUTE_NAME);
  if ($route_name !== 'cl_server.render') {
    return;
  }
  $uri = implode('/', [$request->getSchemeAndHttpHost(), ltrim($uri, '/')]);
}
