# Schema for the configuration files of the static_export_data_resolver_graphql module.
static_export_data_resolver_graphql.settings:
  type: config_object
  label: 'Static Export GraphQL Data Resolver settings'
  mapping:
    dir:
      type: string
      label: 'Directory for .gql files'
