config_notify.settings:
    path: '/admin/config/development/configuration/notify'
    defaults:
      _form: '\Drupal\config_notify\Form\ConfigNotifySettingsForm'
      _title: 'Config notify configuration'
    requirements:
      _permission: 'synchronize configuration'
