<?php

use Drupal\Core\Url;

/**
 * Implements hook_theme().
 *
 * Provides theme registration for themes.
 */
function static_suite_theme(): array {
  return [
    'toolbar_progress_bar' => [
      'variables' => [
        'batchUri' => NULL,
        'title' => NULL,
        'label' => NULL,
        'percent' => NULL,
        'message' => NULL,
      ],
    ],
  ];
}

/**
 * Check if conditions to show the progress bar in the toolbar are met.
 *
 * @param string $permission
 *   The user permission to check.
 *
 * @return bool
 *   Render status.
 */
function static_suite_is_progress_bar_in_toolbar_allowed(string $permission): bool {
  $requestUri = Drupal::service('request_stack')->getCurrentRequest()
    ->getRequestUri();
  $isReportsPage = strpos($requestUri, Url::fromRoute('static_suite.admin_reports')
    ->toString());
  $isBatchPage = strpos($requestUri, Url::fromRoute('system.batch_page.html')
    ->toString());
  $userHasPermission = Drupal::currentUser()->hasPermission($permission);
  $adminContext = Drupal::service('router.admin_context');

  if ($isReportsPage !== FALSE || $isBatchPage !== FALSE || !$userHasPermission || !$adminContext->isAdminRoute()) {
    return FALSE;
  }
  return TRUE;
}

/**
 * Returns the toolbar progress bar theme.
 *
 * @param string $uri
 *   The batch uri.
 * @param string|array $title
 *   The title of the progress bar. A string or a render array.
 *
 * @return array
 *   Render array.
 */
function static_suite_progress_bar_theme(string $uri, string|array $title): array {
  return [
    '#theme' => 'toolbar_progress_bar',
    '#title' => $title,
    '#batchUri' => $uri,
    '#attached' => [
      'drupalSettings' => [
        'batch' => [
          'delay' => 3000,
          'errorMessage' => t('An error has occurred.'),
          'initMessage' => t('Gathering data...'),
          'finishMessage' => t('Process finished'),
          'nextStepMessage' => t('New process found, reloading...'),
        ],
      ],
      'library' => [
        'static_suite/batch-toolbar',
      ],
    ],
  ];
}