#!/usr/bin/env bash
set -e
. "$YCLI_WORKDIR/common"

cli_help_deploy() {
  echo "
Command: getuuid

Usage: 
  getuuid project_name"
  exit 1
}

[ ! -n "$1" ] && cli_help_deploy

export YCLI_PROJECT_NAME=$1

cli_log "Get UUID BEGIN"

cli_log "ENV variables"
env | grep "YCLI_*"

cli_log "Parsing system.site.yml"

cd ~/ystart/configs

function parse_yaml {
   local prefix=$2
   local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
   sed -ne "s|^\($s\):|\1|" \
        -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
   awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
         printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
      }
   }'
}

eval $(parse_yaml system.site.yml)
echo $uuid

# Example

# helm upgrade --install \
#   --wait \
#   --values $YCLI_PROJECTS_PATH/$YCLI_PROJECT_NAME/values.yaml \
#   --namespace $YCLI_K8S_NAMESPACE $YCLI_PROJECT_NAME $YCLI_REPO_PATH

cli_log "Deployment END"
