name: Feeds As Configuration
description: Allows feed entities to be exported/imported as configuration.
package: Structure
type: module
php: 7.4
core_version_requirement: ^8.8 || ^9 || ^10
dependencies:
  - content_as_config:content_as_config
  - drupal:feeds

# Information added by Drupal.org packaging script on 2022-07-07
version: '1.0.6'
project: 'content_as_config'
datestamp: 1657204976
