replicaCount: 1

image:
  repository: ghcr.io/heremias/sid-y-master
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "d39fe6e888c6f3f284a1de47d66550888fdc8484"

imagePullSecrets:
  - name: wise

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

configMap:
  name: ysite

ingress:
  enabled: false
