apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "ysite-chart.labels" . | nindent 4 }}
  name: {{ include "ysite-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ysite-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ysite-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 80
          name: http
        - containerPort: 8080
          name: http-alt
      imagePullSecrets:
        - name: wise
