apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "ysite-chart.labels" . | nindent 4 }}
  name: {{ include "ysite-chart.fullname" . }}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http-alt
  selector:
    {{- include "ysite-chart.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
