# Schema for the configuration files of the static_builder_codebuild module.
static_builder_codebuild.settings:
  type: config_object
  label: 'Static Builder - AWS Codebuild settings'
  mapping:
    project:
      type: string
      label: 'AWS Codebuild project name'
    region:
      type: string
      label: 'AWS Region'
